name: Playwright Tests

on:
  push:
    branches:
      - master
      - codeceptjs
  pull_request:
    branches:
      - master
      - codeceptjs

env:
  CI: true
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: microsoft/playwright-github-action@v1
    - name: install required packages
      run: |
        sudo apt-get install php
    - name: npm install
      run: |
        npm install
    - name: start a server
      run: "php -S 127.0.0.1:8000 -t test/data/app &"
    - name: run chromium tests
      run: "BROWSER=chromium node ./POC/tests --debug"
    - name: run firefox tests
      run: "BROWSER=firefox node ./POC/tests --debug"
    - name: run webkit tests
      run: "BROWSER=webkit node ./POC/tests --debug"
   
